name: itio_editor
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  cached_network_image: ^3.3.1
  image_cropper: ^8.0.1

  flutter_quill: ^10.8.5
  flutter_quill_extensions: ^10.8.5

  gif_view: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: SBL_Hebrew
      fonts:
        - asset: assets/fonts/SBL_Hbrw.ttf
    - family: GentiumPlus
      fonts:
        - asset: assets/fonts/GentiumPlus-Bold.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
